name: Deploy Bicep to Azure

on:
  push:
    branches:
      - master  # Trigger on push to master
  workflow_dispatch:  # Allows manual triggering from GitHub UI
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Granting write access to the id-token

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Set up Azure CLI
      #  uses: azure/setup-azurecli@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Build Bicep and Deploy to Resource Group
        run: |
          az bicep build --file ./vm-public-subnet.bicep
          az deployment group create --resource-group test-env-grp --template-file ./vm-public-subnet.json --parameters adminUsername="${{ secrets.ADMIN_USER }}" adminPassword="${{ secrets.ADMIN_PASSWORD }}"
