name: Deploy Bicep to Azure

on:
  push:
    branches:
      - master  # Adjust to your preferred branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can keep this as is or use a specific runner version like ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI (v2)
      uses: azure/setup-azurecli@v2  # Updated to v2 to avoid errors with version v1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Bicep CLI
      run: az bicep install

    - name: Build Bicep and Deploy to Resource Group
      run: |
        # Build the Bicep file into an ARM template
        az bicep build --file ./vm-public-subnet.bicep
        # Deploy the Bicep file to the resource group
        az deployment group create --resource-group test-env-grp --template-file ./vm-public-subnet.json --parameters adminUsername="adminuser" adminPassword="${{ secrets.ADMIN_PASSWORD }}"
