name: Deploy Bicep to Azure

on:
  push:
    branches:
      - master  # Adjust this based on your branch or trigger conditions
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ensure this is a stable runner version

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3  # Use a specific patch version for checkout

    # Step 2: Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v2  # Use the latest stable version

    # Step 3: Login to Azure using a Service Principal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 4: Install Bicep CLI
    - name: Install Bicep CLI
      run: az bicep install

    # Step 5: Build Bicep and Deploy to Resource Group
    - name: Build Bicep and Deploy to Resource Group
      run: |
        # Build the Bicep file into an ARM template (JSON)
        az bicep build --file ./vm-public-subnet.bicep
        # Deploy the Bicep file to the resource group
        az deployment group create --resource-group test-env-grp --template-file ./vm-public-subnet.json --parameters adminUsername="adminuser" adminPassword="${{ secrets.ADMIN_PASSWORD }}"
