name: Deploy Bicep to Azure

on:
  push:
    branches:
      - master  # Trigger on push to master
      
  workflow_dispatch:  # Allows manual triggering from GitHub UI
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Granting write access to the id-token
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Load environment variables from env_variables.txt
        run: |
          cat ./env_variables.txt
          export $(grep -v '^#' ./env_variables.txt | xargs)
          echo "Resource Group Name: $RESOURCE_GROUP_NAME"
   

      - name: Build Bicep and Deploy to Resource Group
        run: |
          bicep build main.bicep
          az deployment group create --resource-group "$RESOURCE_GROUP_NAME" --template-file ./main.bicep --parameters adminUsername="${{ secrets.ADMIN_USER }}" adminPassword="${{ secrets.ADMIN_PASSWORD }}" --mode Complete



