name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main  # You can adjust this based on your branch or trigger conditions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    # Step 3: Login to Azure using a Service Principal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 4: Install Bicep CLI
    - name: Install Bicep CLI
      run: az bicep install

    # Step 5: Deploy Bicep template to Azure
    - name: Deploy Bicep template
      run: |
        az bicep build --file main.bicep
        az deployment group create --resource-group test-env-grp --template-file ./vm-public-subnet.bicep --parameters adminUsername="adminuser" adminPassword="Password123!"
